---
site_name: tKAP
site_description: Website and documentation for tKAP project
site_author: Particule
site_url: https://particuleio.github.io/tkap/

repo_name: particuleio/tkap
repo_url: https://github.com/particuleio/tkap

copyright: <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a>

theme:
  name: 'material'
  logo: "images/logo-light-picto.svg"
  features:
    - tabs
    - instant

markdown_extensions:
  - toc:
      permalink: true
  - markdown_include.include
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

nav:
  - Overview: index.md
