name: 'terraform:env:demo'

on:
  push:
    branches:
    - master
    paths:
    - 'terraform/live/demo/**'
  pull_request:

jobs:
  terraform:
    name: 'terragrunt:env:demo'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: 'asdf:install'
      uses: asdf-vm/actions/install@v1.0.0

    - name: 'terraform:setup'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: true
        terraform_version: 0.13.2

    - name: 'aws:credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: 'terraform:fmt:kapsule'
      run: terraform fmt -check
      working-directory: terraform/live/demo/fr-par/kapsule

    - name: 'terraform:init:kapsule'
      run: terraform init
      working-directory: terraform/live/demo/fr-par/kapsule

    - name: 'terraform:plan:kapsule'
      run: terraform plan
      working-directory: terraform/live/demo/fr-par/kapsule

    - name: 'terraform:apply:kapsule'
      run: terraform apply -auto-approve
      working-directory: terraform/live/demo/fr-par/kapsule

    - name: 'terraform:destroy:kapsule'
      run: terraform destroy -auto-approve
      working-directory: terraform/live/demo/fr-par/kapsule
      if: "!contains(github.event.head_commit.message, 'ci keep')"
